"""Plain forward-state plots with editable LaTeX ATRA window annotations."""
import json

import matplotlib.pyplot as plt
from matplotlib.colors import to_rgb
from matplotlib.lines import Line2D
from matplotlib.ticker import MaxNLocator
import numpy as np


def make_forward(data_dir, out_dir, panels, height):
    data = np.load(data_dir / "forward_trajectories.npz")
    states = data["states"].tolist()
    regimes = data["regimes"].tolist()
    colors = ["#1f77b4", "#ff7f0e", "#7f7f7f", "#cc3333"]
    short = ["Normal", "Early", "Advanced", "Severe APC"]
    width = 14.6
    with plt.rc_context({"axes.grid": False, "axes.facecolor": "white",
                         "figure.facecolor": "white"}):
        fig, axes = plt.subplots(1, 2, figsize=(width, height))
        fig.subplots_adjust(left=.085, right=.965, bottom=1.20/height,
                            top=1-1.15/height, wspace=.23)
        windows = []
        for ax, (state, title) in zip(axes, panels):
            index = states.index(state)
            for regime, color in enumerate(colors):
                ax.plot(data["t"], data["reference"][regime, :, index],
                        color=color, lw=3.4, alpha=.56, solid_capstyle="round")
                ax.plot(data["t"], data["pinn"][regime, :, index],
                        color=tuple(.60*v for v in to_rgb(color)), lw=1.8,
                        ls=(0, (5.5, 3.5)))
            ax.set_xlim(0, 150)
            ax.set_xticks([0, 50, 100, 150])
            ax.yaxis.set_major_locator(MaxNLocator(nbins=4, min_n_ticks=3))
            ax.margins(y=.075)
            ax.grid(False, which="both")
            ax.set_facecolor("white")
            ax.spines[["top", "right"]].set_visible(False)
            ax.tick_params(length=4, width=.9, labelsize=23)
            pos = ax.get_position()
            fig.text(pos.x0, (height-.36)/height, title,
                     ha="left", va="center", fontsize=28)
            windows.append({
                "state": state,
                "left": width*(pos.x0+pos.width*float(data["tau1"])/150),
                "right": width*(pos.x0+pos.width*float(data["tau2"])/150),
                "y": height*pos.y1+.12,
            })
        axes[0].set_ylabel("concentration", fontsize=24, labelpad=9)
        fig.text(.54, .60/height, r"dimensionless time $\tau$",
                 fontsize=24, ha="center", va="center")
        handles = [Line2D([], [], color=c, lw=3.4, alpha=.75, label=n)
                   for c, n in zip(colors, short)]
        handles.append(Line2D([], [], color=".35", lw=1.8,
                              ls=(0, (5.5, 3.5)), label="PINN (dashed)"))
        fig.legend(handles=handles, loc="lower center", ncol=5,
                   bbox_to_anchor=(.54, 0), fontsize=23, frameon=False,
                   handlelength=1.65, columnspacing=1.25, handletextpad=.55,
                   borderaxespad=0, borderpad=.1)
        fig.savefig(out_dir / "forward.pdf")
        fig.savefig(out_dir / "forward.png", dpi=110)
        plt.close(fig)

    # Plot curves remain vector PDF. Window arrows and labels are native TikZ,
    # located from the actual axis transform, exactly at tau=40 and tau=88.
    tex = ["% Generated by figures/forward_plot.py; ATRA annotations are native LaTeX.",
           r"\begingroup", r"\begin{tikzpicture}[x=1in,y=1in]",
           r"\node[anchor=south west,inner sep=0pt] at (0,0)"
           r" {\includegraphics[width=14.6in]{assets/forward.pdf}};"]
    for w in windows:
        tex.append(
            r"\draw[{Stealth[length=8pt,width=7pt]}-{Stealth[length=8pt,width=7pt]},"
            r"draw=Ink!80,line width=1.7pt]"
            f" ({w['left']:.5f},{w['y']:.5f}) --"
            r" node[above=5pt,font=\fontsize{24}{29}\selectfont,text=Ink] {ATRA}"
            f" ({w['right']:.5f},{w['y']:.5f});")
    tex += [r"\end{tikzpicture}%", r"\endgroup"]
    (out_dir / "forward-window.tex").write_text("\n".join(tex)+"\n")
    (out_dir / "forward_plot_audit.json").write_text(json.dumps({
        "states": [p[0] for p in panels], "regimes": regimes,
        "pulse": [float(data["tau1"]), float(data["tau2"])],
        "grid": False, "background": "white", "arrow": "<->",
        "label": "ATRA", "label_position": "above", "windows_inches": windows,
        "size_inches": [width, height],
    }, indent=2)+"\n")
