"""Model definitions with no device, dtype or environment side effects."""

from copy import deepcopy

MODEL_VERSION = "wnt-ra-hox-runtime-v1"
STATE_ORDER = ("b", "p", "h5", "h13", "m", "r", "c")
INITIAL_STATE = (0.20, 1.00, 0.80, 0.30, 0.30, 0.60, 0.40)

BASELINE = {'W': 0.8,
 'thetaP': 1.0,
 'nB': 2,
 'nM': 2,
 'nH': 2,
 'eta13': 0.75,
 'kappa13': 0.55,
 'lambdaP': 1.6,
 'lambda5': 1.3,
 'kappa5': 0.5,
 'epsP': 1.0,
 'rho5': 1.1,
 'rhoB': 1.1,
 'rho13': 1.3,
 'deltaP1': 3.5,
 'eps5': 1.2,
 'a5': 0.15,
 'etaR': 2.5,
 'kappaR': 0.4,
 'etaM': 2.5,
 'kappaM': 0.5,
 'eps13': 1.0,
 'a13': 0.18,
 'etaB13': 0.95,
 'kappaB13': 0.5,
 'etaM13': 0.55,
 'kappaM13': 0.5,
 'epsM': 0.6,
 'aM': 0.18,
 'etaBM': 1.35,
 'kappaBM': 0.5,
 'epsR': 0.4,
 'lambdaC': 0.85,
 'epsC': 0.8,
 'aC': 0.08,
 'etaRC': 1.5,
 'kappaRC': 0.5,
 'etaBC': 1.5,
 'kappaBC': 0.5,
 'mu0': 0.35,
 'AR': 0.04,
 'TR': 24.0,
 'phi': 0.0,
 'DR': 1.5,
 'q': 0.3,
 'tau1': 40.0,
 'tau2': 88.0,
 'alpha13': 1.0,
 'alpha5': 1.0,
 'DW': 0.0,
 'qW': 0.3,
 'tauW1': 40.0,
 'tauW2': 80.0,
 'DM': 0.0,
 'qM': 0.3,
 'tauM1': 40.0,
 'tauM2': 80.0,
 'kW': 1.0,
 'k13': 1.0,
 'ka5': 1.0,
 'ka13': 1.0,
 'kaM': 1.0,
 'kaC': 1.0}

REGIMES = {'Normal': {'W': 0.8, 'thetaP': 1.0},
 'Early Adenoma': {'W': 1.0, 'thetaP': 0.75},
 'Advanced Adenoma': {'W': 1.5, 'thetaP': 0.5},
 'Severe APC Loss': {'W': 2.0, 'thetaP': 0.25}}

CONDITIONS = [{'name': 'ctrl', 'forcing': {}},
 {'name': 'noATRA', 'forcing': {'DR': 0.0}},
 {'name': 'earlyATRA', 'forcing': {'DR': 2.5, 'tau1': 20.0, 'tau2': 55.0}},
 {'name': 'lateATRA', 'forcing': {'DR': 2.0, 'tau1': 90.0, 'tau2': 130.0}},
 {'name': 'lowATRA', 'forcing': {'DR': 0.6, 'tau1': 40.0, 'tau2': 80.0}},
 {'name': 'strongCirc', 'forcing': {'AR': 0.12, 'DR': 0.0}},
 {'name': 'wntPulse', 'forcing': {'DW': 1.0, 'tauW1': 30.0, 'tauW2': 70.0}},
 {'name': 'wntInhib', 'forcing': {'DW': -0.7, 'tauW1': 50.0, 'tauW2': 200.0}},
 {'name': 'mycPulse', 'forcing': {'DM': 1.2, 'tauM1': 30.0, 'tauM2': 70.0}},
 {'name': 'wntRAcombo',
  'forcing': {'DW': 0.8,
              'tauW1': 25.0,
              'tauW2': 200.0,
              'DR': 2.0,
              'tau1': 40.0,
              'tau2': 80.0}}]

FIXED = {'AR',
 'DM',
 'DR',
 'DW',
 'TR',
 'alpha13',
 'alpha5',
 'k13',
 'kW',
 'ka13',
 'ka5',
 'kaC',
 'kaM',
 'mu0',
 'nB',
 'nH',
 'nM',
 'phi',
 'q',
 'qM',
 'qW',
 'tau1',
 'tau2',
 'tauM1',
 'tauM2',
 'tauW1',
 'tauW2'}

HYBRID_TERMS = {'ra_h5': {'inputs': ['r'],
           'replaces': ['etaR', 'kappaR'],
           'eq': 'dh5',
           'mono': (1,),
           'anchor': 0.0,
           'u_max': 2.5,
           'basal': 'a5'},
 'bm_myc': {'inputs': ['b'],
            'replaces': ['etaBM', 'kappaBM'],
            'eq': 'dm',
            'mono': (1,),
            'anchor': 0.0,
            'u_max': 1.35,
            'basal': 'aM'},
 'b_h13': {'inputs': ['b'],
           'replaces': ['etaB13', 'kappaB13'],
           'eq': 'dh13',
           'mono': (1,),
           'anchor': 0.0,
           'u_max': 0.95,
           'basal': 'a13'},
 'bc_cyp': {'inputs': ['b'],
            'replaces': ['etaBC', 'kappaBC'],
            'eq': 'dc',
            'mono': (1,),
            'anchor': 0.0,
            'u_max': 1.5,
            'basal': 'aC'},
 'rc_cyp': {'inputs': ['r'],
            'replaces': ['etaRC', 'kappaRC'],
            'eq': 'dc',
            'mono': (1,),
            'anchor': 0.0,
            'u_max': 1.5,
            'basal': 'aC'},
 'm_h13': {'inputs': ['m'],
           'replaces': ['etaM13', 'kappaM13'],
           'eq': 'dh13',
           'mono': (1,),
           'anchor': 0.0,
           'u_max': 0.55,
           'basal': 'a13'},
 'h13_b': {'inputs': ['h13'],
           'replaces': ['eta13', 'kappa13'],
           'eq': 'db',
           'mono': (1,),
           'anchor': 0.0,
           'u_max': 0.75,
           'basal': 'W'},
 'm_h5': {'inputs': ['m'],
          'replaces': ['etaM', 'kappaM'],
          'eq': 'dh5',
          'mono': (1,),
          'anchor': 0.0,
          'u_max': 2.5,
          'factor': 'h5'},
 'h5_b': {'inputs': ['b'],
          'replaces': ['lambda5', 'kappa5'],
          'eq': 'db',
          'mono': (1,),
          'anchor': 0.0,
          'u_max': 1.3,
          'factor': 'h5'},
 'apc_b': {'inputs': ['apc'],
           'replaces': ['lambdaP'],
           'eq': 'db',
           'mono': (1,),
           'anchor': 0.0,
           'u_max': None,
           'factor': 'b'},
 'c_ra': {'inputs': ['c'],
          'replaces': ['lambdaC'],
          'eq': 'dr',
          'mono': (1,),
          'anchor': 0.0,
          'u_max': None,
          'factor': 'r'},
 'apc_prod': {'inputs': ['h5', 'b', 'h13'],
              'replaces': ['rho5', 'rhoB', 'rho13'],
              'eq': 'dapc',
              'mono': (1, -1, -1),
              'anchor': None,
              'u_max': 3.0},
 'apc_mutation': {'inputs': ['thetaP'],
                  'replaces': ['deltaP1'],
                  'eq': 'dapc',
                  'input_kind': 'parameter',
                  'mono': (1,),
                  'anchor': 0.0,
                  'u_max': 3.5}}

UNKNOWN = tuple(name for name in BASELINE if name not in FIXED)

def parameters(regime="Normal", overrides=None):
    """Return an independent parameter dictionary for a named regime."""
    if regime not in REGIMES:
        raise ValueError(f"Unknown regime: {regime}")
    result = {**BASELINE, **REGIMES[regime]}
    if overrides:
        unknown = set(overrides) - set(BASELINE)
        if unknown:
            raise ValueError(f"Unknown model parameters: {sorted(unknown)}")
        result.update(overrides)
    return result

def conditions():
    """Return the ten documented intervention protocols."""
    return deepcopy(CONDITIONS)

Y0 = INITIAL_STATE
VAR_NAMES = ["b", "p", r"$h_5$", r"$h_{13}$", "m", "r", "c"]
